# This is the volume configuration we want
# As we have not the right to define it, I keep it as a reference only
# It may be wrong, it has never been tested

- name: phd-assess zeebe volume
  openshift:
    state: latest
    resource: Storage
    name: "{{ svc_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: local-storage
        finalizers:
          - kubernetes.io/pvc-protection
        name: "{{ volume_zeebe_name }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
