# Production inventory
# N.B.: groups and group variables are defined in ../inventory.yml

all:
  children:
    openshift_namespaces:
      hosts:
        phd-assess:
          notifier_port: "25"
          notifier_host: "mail.epfl.ch"
          notifier_from_address: "Annual report <noreply@epfl.ch>"
